version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/vue"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
